// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RequestService.Infrastructure.Data;

#nullable disable

namespace RequestService.Infrastructure.Migrations
{
    [DbContext(typeof(RequestServiceContext))]
    [Migration("20260611193929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RequestService.Core.Entities.ArtworkRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AgreedDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AgreedDeliveryTime")
                        .HasColumnType("text");

                    b.Property<decimal?>("AgreedPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ArtworkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deliverable")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgressMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProposedDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProposedDeliveryTime")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProposedPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequesterUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("RequesterId");

                    b.ToTable("ArtworkRequests");
                });

            modelBuilder.Entity("RequestService.Core.Entities.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<decimal?>("PayloadBudget")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PayloadDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadNote")
                        .HasColumnType("text");

                    b.Property<decimal?>("PayloadPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("RequestService.Core.Entities.RequestMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestMessages");
                });

            modelBuilder.Entity("RequestService.Core.Entities.RequestLog", b =>
                {
                    b.HasOne("RequestService.Core.Entities.ArtworkRequest", "Request")
                        .WithMany("Logs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("RequestService.Core.Entities.RequestMessage", b =>
                {
                    b.HasOne("RequestService.Core.Entities.ArtworkRequest", "Request")
                        .WithMany("Messages")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("RequestService.Core.Entities.ArtworkRequest", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
